In [1]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Word Embedding using One-Hot Encoding"
      ],
      "metadata": {
        "id": "jTTtpq73PnQI"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "61isDZjKKcGn"
      },
      "outputs": [],
      "source": [
        "from sklearn.preprocessing import OneHotEncoder"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "words = [['cat'],['dog'],['apple'],['car']]"
      ],
      "metadata": {
        "id": "m9vvwOP2QmiN"
      },
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "encoder = OneHotEncoder(sparse_output=False)\n",
        "result = encoder.fit_transform(words)"
      ],
      "metadata": {
        "id": "NMKE3p6lQ-Yt"
      },
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"words :\",encoder.categories_[0])\n",
        "print(\"Embeddings:\")\n",
        "print(result)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4uFghIpVRqkx",
        "outputId": "001f0eb9-1536-4add-ae01-e566b12d8e3e"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "words : ['apple' 'car' 'cat' 'dog']\n",
            "Embeddings:\n",
            "[[0. 0. 1. 0.]\n",
            " [0. 0. 0. 1.]\n",
            " [1. 0. 0. 0.]\n",
            " [0. 1. 0. 0.]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "['apple' 'car' 'cat' 'dog']\n",
        "['apple' 'car' 'cat' 'dog']\n",
        "['apple' 'car' 'cat' 'dog']\n",
        "['apple' 'car' 'cat' 'dog']"
      ],
      "metadata": {
        "id": "ICgb7EKBShE4"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Find Similar Words using Word2Vec"
      ],
      "metadata": {
        "id": "bpLJMZWNURwe"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install gensim"
      ],
      "metadata": {
        "id": "Qtud7K4oUbm5",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "f015ea3d-252c-4197-d766-3935eae90313"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting gensim\n",
            "  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)\n",
            "Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)\n",
            "Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)\n",
            "Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)\n",
            "Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.1)\n",
            "Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m27.8/27.8 MB\u001b[0m \u001b[31m48.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: gensim\n",
            "Successfully installed gensim-4.4.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from gensim.models import Word2Vec"
      ],
      "metadata": {
        "id": "69pkP2uwVT-t"
      },
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "sentences = [[\"python\",\"is\",\"a\",\"language\"],\n",
        " [\"java\",\"is\",\"a\",\"language\"],\n",
        "  [\"python\",\"is\",\"easy\"],\n",
        "   [\"java\",\"is\",\"easy\"],\n",
        "    [\"python\",\"is\",\"powerful\"],\n",
        "     [\"java\",\"is\",\"powerful\"]]"
      ],
      "metadata": {
        "id": "-gZcoqQSVl5o"
      },
      "execution_count": 8,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "model = Word2Vec(sentences,vector_size=10,window=2,min_count=1,workers=1)"
      ],
      "metadata": {
        "id": "6F9AX9ivWbyh"
      },
      "execution_count": 9,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "print(model.wv.most_similar('java',topn=3))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "B5lR7DgCX00p",
        "outputId": "fd958f6f-3493-4f11-9b4a-d0cef95971a3"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[('is', 0.5436059236526489), ('python', 0.3293713927268982), ('a', -0.17999078333377838)]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(model.wv.most_similar('python',topn=4))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ntaeGj7iYeUv",
        "outputId": "6ea7caa5-46e6-4b72-bcb6-aed9f6204577"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[('java', 0.3293713331222534), ('is', 0.3004249036312103), ('a', -0.08937527984380722), ('powerful', -0.1055101677775383)]\n"
          ]
        }
      ]
    }
  ]
}

{'nbformat': 4,
 'nbformat_minor': 0,
 'metadata': {'colab': {'provenance': []},
  'kernelspec': {'name': 'python3', 'display_name': 'Python 3'},
  'language_info': {'name': 'python'}},
 'cells': [{'cell_type': 'markdown',
   'source': ['Word Embedding using One-Hot Encoding'],
   'metadata': {'id': 'jTTtpq73PnQI'}},
  {'cell_type': 'code',
   'execution_count': 1,
   'metadata': {'id': '61isDZjKKcGn'},
   'outputs': [],
   'source': ['from sklearn.preprocessing import OneHotEncoder']},
  {'cell_type': 'code',
   'source': ["words = [['cat'],['dog'],['apple'],['car']]"],
   'metadata': {'id': 'm9vvwOP2QmiN'},
   'execution_count': 2,
   'outputs': []},
  {'cell_type': 'code',
   'source': ['encoder = OneHotEncoder(sparse_output=False)\n',
    'result = encoder.fit_transform(words)'],
   'metadata': {'id': 'NMKE3p6lQ-Yt'},
   'execution_count': 3,
   'outputs': []},
  {'cell_type': 'code',
   'source': ['print("words :",encoder.categories_[0])\n',
    'print("Embeddings:")\n',
    'prin